//
// Generated file, do not edit! Created by opp_msgtool 6.0 from customMessage.msg.
//

#ifndef __CUSTOMMESSAGE_M_H
#define __CUSTOMMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class customMessage;
/**
 * Class generated from <tt>customMessage.msg:4</tt> by opp_msgtool.
 * <pre>
 * message customMessage
 * {
 *     int message_type = 0;
 *     int gate_num = 0;
 *     int uncertainty = 0;
 * }
 * </pre>
 */
class customMessage : public ::omnetpp::cMessage
{
  protected:
    int message_type = 0;
    int gate_num = 0;
    int uncertainty = 0;

  private:
    void copy(const customMessage& other);

  protected:
    bool operator==(const customMessage&) = delete;

  public:
    customMessage(const char *name=nullptr, short kind=0);
    customMessage(const customMessage& other);
    virtual ~customMessage();
    customMessage& operator=(const customMessage& other);
    virtual customMessage *dup() const override {return new customMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMessage_type() const;
    virtual void setMessage_type(int message_type);

    virtual int getGate_num() const;
    virtual void setGate_num(int gate_num);

    virtual int getUncertainty() const;
    virtual void setUncertainty(int uncertainty);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const customMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, customMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline customMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<customMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CUSTOMMESSAGE_M_H

